import {
	type EnkoreAutogeneratedFile,
	createEntity
} from "@enkore/spec"
import type {Options} from "./Options.mts"
import type {Variant} from "./Variant.mts"
import {destinationPathToFunctionName} from "./destinationPathToFunctionName.mts"
import {_generateFactoryCode} from "./_generateFactoryCode.mts"

export function _generateFactoryFile(
	options: Options, variant: Variant
): EnkoreAutogeneratedFile {
	const exportName = destinationPathToFunctionName(
		options.destination
	).slice(0, -("Factory".length))

	return createEntity("EnkoreAutogeneratedFile", 0, 0, {
		destinationPath: options.destination,
		generator(session) {
			return _generateFactoryCode(
				session,
				options,
				exportName,
				variant
			)
		}
	})
}
