import type {EnkoreAutogeneratedFile} from "@enkore/spec"
import type {Options} from "./Options.mts"
import type {Variant} from "./Variant.mts"

export type Generator = (
	options: Options,
	// this is to be able to tell if expand() was used
	// users should never set this value
	__internalIsAsyncSyncVariant?: Variant
) => EnkoreAutogeneratedFile[]
